# Generated by Django 5.0.6 on 2024-05-25 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurApp', '0002_user_is_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapportText', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemmandAllRapports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canGetAllR', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_demmandallrapports', to=settings.AUTH_USER_MODEL)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecin_demmandallrapports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('client', 'medecin')},
            },
        ),
        migrations.CreateModel(
            name='MesPatiens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_mespations', to=settings.AUTH_USER_MODEL)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecin_mespations', to=settings.AUTH_USER_MODEL)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OurApp.rapport')),
            ],
            options={
                'unique_together': {('client', 'medecin', 'rapport')},
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_rendezvous', to=settings.AUTH_USER_MODEL)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecin_rendezvous', to=settings.AUTH_USER_MODEL)),
                ('rapport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OurApp.rapport')),
            ],
            options={
                'unique_together': {('client', 'medecin')},
            },
        ),
    ]
