# Generated by Django 5.0.6 on 2024-05-25 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurApp', '0003_rapport_demmandallrapports_mespatiens_rendezvous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='rapport',
        ),
        migrations.AddField(
            model_name='rapport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
